services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: muxer:latest
    container_name: muxer
    tty: true
    volumes:
      - ./input/:/app/data/input
      - ./output/:/app/data/output
    command: ["--input", "/app/data/input", "--output", "/app/data/output"]