services:
  app:
    image: ghcr.io/mau671/muxer:latest
    container_name: muxer
    tty: true
    volumes:
      - /mnt/downloads/anime/:/app/data
    command: ["--input", "/app/data/input", "--output", "/app/data/output", "--delete-after"]